using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests_Generator.Tests
{
    [TestClass]
    public class AnotherOneTests
    {
        [TestMethod]
        public void TestAndAnotherOne()
        {
            Assert.Fail("autogenerated");
        }
    }
}