using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Shit.Tests
{
    [TestClass]
    public class SuperPuperMegaModuleTests
    {
        [TestMethod]
        public void TestFail()
        {
            Assert.Fail("autogenerated");
        }
    }
}